def dna_profile(dna_sequence):
    symbols = ['A', 'C', 'G', 'T']
    profile = dict(A=0, C=0, G=0, T=0)
    profile['\n'] = 1

    for s in dna_sequence:
        if not s in symbols and not s == '\n':
            print s
            raise ValueError
        profile[s] = profile[s] + 1

    return [profile[i] for i in symbols]

def dna_file_reader(filename, sequence):
    f = open(filename, r)
    s = f.read()


if __name__ == '__main__':
    # print dna_profile('CACGT')
    # print dna_profile('AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC')
    f = open('rosalind_dna.txt', 'r')
    s = f.read()
    print dna_profile(s)

    for i in dna_profile('GACCAGCTCAACTCGGACTGAATAATTCTTCAGACACCCATGATCCAGCTAGTGCATCGACACTGAAGAGAGAATTGCTACCCATATAGTAACGGGATTCCACTAACACCGGAATCTTTAAGCTCTACAATGTTGTAAAAGCCCTCAATTGAATCAGCACAGATGCGATGCGGCTGATAGTCCTTTCGCGACGCTATCCTTTCTCTTAGCCTCCGTATGTCACCAAGAGCGGGCTCACCGGTATTGGGGCGGTCACCGAACATACATGGTACTGCAGAGCAGATTTCAATTCGACTGACGCCATGTTAGGCCAGGGCTTACAGCCTCGGACCTAGCCTCTACTCGATTCTACGCGTACCAGGTCTCTACCCCTCGAGTCTGCCCCCATTACGTGTACGCACGGTCGGTGCACACATGAAATCTGTTAAGAAAAGTTGTTTGTTCTCACTCTCCTCGAAATGATATTCATACACCGCCATGCACTAGTCAGTACAATGTCATAAAGCAACCATGAGACCGCCCATGTATACGTTCCCTTCAAAAGTCAGGAATGATTCGTTCACAAATGAGGATCGCTTTTCGCCGCCTGCCTACCGACACTTAAGTGTTGCAATACAGAGTTTTCACAGTTTTTAAGCCCACAACGGAAAGGAGAAACTATAATGTAAATGAGACAATCAAGAAGTGTATCGGTGCAGTGTCCGGCCGACGCGTGATCTTCGCCGTTACTTGTTCCAGTCGGAGATTCATCTATCTTGTGGAGTGCGATACTTCGCCTCAAGAGCGCGCATTCACGCGGGATACCGACCATGGCCGCGTGTGGGCCACTGTGGGCATGCGCTTGACGACCAGAATCGGGACCTTCAAGAGTCAGCCTTAAGAGGTCATGCCCTAAGACATGACAATTCCACGTGGCAAGGGAAGAGTCATGCCAGCCACGAGCTACCAGATTGCCATGAAAAATCAG'):
        print i
